project_id = "siazopelatvphcyngyor"

[functions.send-newsletter-confirmation]
verify_jwt = false

[functions.unsubscribe-newsletter]
verify_jwt = false

[functions.verify-admin-secret]
verify_jwt = false

[functions.notify-new-registration]
verify_jwt = false

[functions.confirm-appointment]
verify_jwt = false

[functions.appointment-reminder]
verify_jwt = false

[functions.notify-new-appointment]
verify_jwt = false

[functions.create-alma-payment]
verify_jwt = false
